name: 'apply'

on:
  workflow_dispatch:
    inputs:
      class_name:
        description: 'Tap class name'
        required: true
        default: 'demo'

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
        
    - name: Terraform Init
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_ACCESS }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_SECRET }}
      run: terraform init
        
    - name: Create Terraform Workspace
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_ACCESS }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_SECRET }}
      run: terraform workspace new '${{ github.event.inputs.class_name }}'
      continue-on-error: true

    - name: Select Terraform Workspace 
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_ACCESS }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_SECRET }}
      run: terraform workspace select '${{ github.event.inputs.class_name }}'

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check -diff
      # continue-on-error: true

    - name: Terraform Apply
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_ACCESS }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_SECRET }}
      run: terraform apply -auto-approve -var=bootstrap_password='${{ secrets.TAP_USER_PASS }}' --var-file envs/tap-${{ github.event.inputs.class_name }}.tfvars

    - name: Terraform Output
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_IAM_ACCESS }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_IAM_SECRET }}
      run: terraform output